### ISSUE TITLE
Agenda:  Conference Call #2

### ISSUE THREAD

**Issue by grabear** [datasnakes/beRi#23]
Agenda for meeting on **1/22/2019**.

# General Points
* New Issue based meeting notes?
* Coding sessions?
* Cleaning up after hackseq.

# Repo Specific Points
* Rob - Discuss _beRi_
    * Connecting beRi to renv, rut, and rinse.
    * [Configuration](https://github.com/datasnakes/beRi/tree/poetry_branch/beri/cookies) with cookiecutter
    * beRi directory structure _(but remove the package version folders):_
![directory structure](https://user-images.githubusercontent.com/20953530/39461696-3789bd82-4cd2-11e8-915d-3e860969e61c.png)
* Santina/Rob - Discuss _renv_
* Bruno - Discuss _rut_
* Shaurita/Emma - Discuss _rinse_

**Comment by grabear** [comment]
@datasnakes/beri-leads  Feel free to add to this agenda.

**Comment by sdhutchins** [comment]
I like the coding sessions idea. We could call that a code sprint. I've read a lot of teams will do that when they want to get a lot of work done in a short period.

It'd be something like deciding we'll all pick a day to code for like 4 straight hours and tackle issues. Maybe every couple of months.
